# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FlickrExplorer' do
pod 'AFNetworking', '2.2.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVPullToRefresh'
#pod 'SVProgressHD'
pod 'FlickrKit'
pod 'MWPhotoBrowser', '2.1.1'
end

target 'FlickrExplorerTests' do

end

