# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FlickrDemo' do
pod 'AFNetworking', '2.2.1'
pod 'MBProgressHUD', '~> 0.9.1'
end

target 'FlickrDemoTests' do

end

